language: java
jdk:
  - oraclejdk8
env:
  global:
    - "MAVEN_OPTS=-Xmx2536m -XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:-UseGCOverheadLimit"
before_install:
  - "env"
  - "echo 'MAVEN_OPTS = $MAVEN_OPTS'"
script: travis_wait mvn install
